config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "tasks", to: "tasks#index", as: :tasks
  # get 'tasks/new', to: "tasks#new", as: :new_task
  # post "tasks", to: "tasks#create", as: :create_task
  # delete 'tasks/:id', to: 'tasks#destroy', as: :destroy_task
  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch 'tasks/:id', to: 'tasks#update', as: :update_task
  # get "tasks/:id", to: "tasks#show", as: :task
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  def set_task
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>
<%= link_to "Home", tasks_path %>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title,  task_path(task) %>
        <%= link_to "Delete", task_path(task), method: :delete, data: { confirm: "Are you sure?" } %>
        <%= link_to "Update",  edit_task_path(task)%>
    </li>
  <% end %>
</ul>
<br>
<%= link_to  "create new", new_task_path%>

app/views/tasks/new.html.erb
<h1>Create a new task</h1>
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<%= @task.title %>
<%= @task.details %>
<br>
<%= link_to "Home", tasks_path %>
<%= link_to  "create new", new_task_path %>